# -*- coding: utf-8 -*-
"""GCode Mejorado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-ZS1qRmUbJ2f24aF5TO9TNhTP1dmY4_
"""

import re
import matplotlib.pyplot as plt

def detectar_levantamientos_lapiz(file_path):
    """
    Detecta donde el plotter debe levantar el lápiz basado en comandos G0
    """
    indices_levantamiento = []
    coordenadas_x = []
    coordenadas_y = []
    patron_g0 = re.compile(r'^(G0|G00)\s')
    patron_g1 = re.compile(r'^(G1|G01)\s')

    x_pattern = r'X([-]?\d*\.?\d+)'
    y_pattern = r'Y([-]?\d*\.?\d+)'

    lapiz_abajo = False
    indice_actual = 0

    try:
        with open(file_path, 'r') as file:
            for line_num, line in enumerate(file, 1):
                line = line.strip()

                # Buscar coordenadas en cualquier línea
                x_match = re.search(x_pattern, line)
                y_match = re.search(y_pattern, line)

                if x_match or y_match:
                    # Si encontramos coordenadas, actualizamos las posiciones
                    current_x = float(x_match.group(1)) if x_match else coordenadas_x[-1] if coordenadas_x else 0
                    current_y = float(y_match.group(1)) if y_match else coordenadas_y[-1] if coordenadas_y else 0

                    coordenadas_x.append(current_x)
                    coordenadas_y.append(current_y)

                    # Detectar cambio de estado del lápiz
                    if patron_g0.match(line):
                        # G0 = movimiento rápido (lápiz levantado)
                        if lapiz_abajo:
                            indices_levantamiento.append(indice_actual)
                            lapiz_abajo = False
                    elif patron_g1.match(line):
                        # G1 = movimiento de dibujo (lápiz abajo)
                        if not lapiz_abajo and indice_actual > 0:
                            # Marcamos el inicio del nuevo segmento de dibujo
                            indices_levantamiento.append(indice_actual)
                        lapiz_abajo = True
                    else:
                        # Para otros comandos, mantenemos el estado actual
                        pass

                    indice_actual += 1

    except Exception as e:
        print(f"Error al procesar el archivo: {e}")

    return indices_levantamiento, coordenadas_x, coordenadas_y

def graficar_con_levantamientos(coordenadas_x, coordenadas_y, indices_levantamiento):
    """
    Grafica el trazado marcando los puntos donde se levanta el lápiz
    """
    plt.figure(figsize=(35, 35))

    # Dibujar todos los puntos
    plt.plot(coordenadas_x, coordenadas_y, 'b-', linewidth=1, alpha=0.7, label="Trayectoria")

    # Marcar puntos donde se levanta el lápiz
    if indices_levantamiento:
        x_levantamientos = [coordenadas_x[i] for i in indices_levantamiento]
        y_levantamientos = [coordenadas_y[i] for i in indices_levantamiento]
        plt.scatter(x_levantamientos, y_levantamientos,
                   color='red', s=80, marker='X',
                   label=f'Levantamientos ({len(indices_levantamiento)})',
                   zorder=5)

    # Marcar inicio y fin
    plt.plot(coordenadas_x[0], coordenadas_y[0], 'go', markersize=10, label='Inicio')
    plt.plot(coordenadas_x[-1], coordenadas_y[-1], 'ro', markersize=10, label='Fin')

    plt.title(f"Trazado con {len(indices_levantamiento)} levantamientos de lápiz", fontsize=14)
    plt.xlabel("Eje X")
    plt.ylabel("Eje Y")
    plt.grid(True, alpha=0.3)
    plt.axis('equal')
    plt.legend()
    plt.tight_layout()
    plt.show()

def calculate_deltas(coordinates):
    """
    Calcula los deltas (diferencias) entre coordenadas consecutivas
    """
    deltas = []
    for i in range(1, len(coordinates)):
        delta = coordinates[i] - coordinates[i-1]
        deltas.append(round(delta, 6))  # Redondear a 6 decimales
    return deltas

# Progama principal
if __name__ == "__main__":
    file_path = "gcode.txt"

    indices_levantamiento, x, y = detectar_levantamientos_lapiz(file_path)



    scale = 30
    for i in range(len(x)):
        x[i] = round(x[i] * scale)
        y[i] = round(y[i] * scale)

    #Filteamos el indice de lavantamiento esto se debe a que para el matplotlib usamo el punto de inicio y de final
    IndicesFiltrados = []
    lista_original = indices_levantamiento # Renombrado para claridad

# Iteramos hasta el penúltimo elemento para poder comparar con el siguiente (i+1)
    for i in range(len(lista_original) - 1):
    # 1. No es el primer elemento (i != 0)
    # 2. No es el último elemento del rango de la iteración (i != len(lista_original) - 2)
    # 3. El valor actual no es consecutivo con el siguiente valor
      if (i != 0) and (lista_original[i] != lista_original[i+1] - 1):
          IndicesFiltrados.append(lista_original[i] - 2)


    print(IndicesFiltrados)
    # Graficar
    graficar_con_levantamientos(x, y, indices_levantamiento)

    print(calculate_deltas(x))
    print(calculate_deltas(y))
    print(len(calculate_deltas(y)))